apiVersion: v1
kind: Service
metadata:
  name: blocky
spec:
  ports:
    - port: 53
      targetPort: 53
      name: dns
    - port: 4000
      targetPort: 4000
      name: http
  externalIPs:
    - 192.168.10.101
  selector:
    app: blocky

