apiVersion: v1
kind: Service
metadata:
  name: adguard-home
spec:
  ports:
    - port: 53
      targetPort: 53
      name: port53
    - port: 843
      targetPort: 843
      name: port843
    - port: 3000
      targetPort: 3000
      name: port3000
    - port: 5443
      targetPort: 5443
      name: port5443
  externalIPs:
    - 192.168.10.101
  selector:
    app: adguard-home

