apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rackula-data
  namespace: rackula
  labels:
    app: rackula
spec:
  resources:
    requests:
      storage: 512Mi
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
