apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookdrop-location
  namespace: booklore
  labels:
    app: booklore
spec:
  storageClassName: manual
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/services/booklore/bookdrop
