apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books-location
  namespace: booklore
  labels:
    app: booklore
spec:
  resources:
    requests:
      storage: 30Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
