apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookdrop-location
  namespace: booklore
  labels:
    app: booklore
spec:
  resources:
    requests:
      storage: 512Mi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
