apiVersion: v1
kind: PersistentVolume
metadata:
  name: manyfold-db-storage
  namespace: manyfold
  labels:
    app: manyfold
spec:
  storageClassName: manual
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/services/manyfold/db
