apiVersion: v1
kind: PersistentVolume
metadata:
  name: models-location
  namespace: manyfold
  labels:
    app: manyfold
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/services/manyfold/models
