apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-location
  namespace: manyfold
  labels:
    app: manyfold
spec:
  resources:
    requests:
      storage: 100Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
