apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manyfold-db-storage
  namespace: manyfold
  labels:
    app: manyfold
spec:
  resources:
    requests:
      storage: 512Mi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
